#!/bin/sh
# SPDX-License-Identifier: BSD-3-Clause
# Regenerate packaged shaders from the sole HLSL source; normal builds need no shader tools.
set -eu
cd "$(dirname "$0")/.."
shader_tmp=$(mktemp -d)
trap 'rm -rf "$shader_tmp"' EXIT HUP INT TERM
for variant in native web; do
  if [ "$variant" = web ]; then define=-DHIDE_WEBGL=1; else define=; fi
  "${DXC:-dxc}" -HV 2021 -T ps_6_0 -E main -spirv -fspv-target-env=vulkan1.1 \
    $define -I cbits/shaders -Fo "$shader_tmp/$variant.spv" cbits/shaders/cell.hlsl
  spirv-val --target-env vulkan1.1 "$shader_tmp/$variant.spv"
done
spirv-cross "$shader_tmp/native.spv" --msl --msl-version 23000 --msl-decoration-binding --output "$shader_tmp/cell.metal"
spirv-cross "$shader_tmp/web.spv" --es --version 300 --rename-interface-variable in 0 vertexColor \
  --rename-interface-variable in 1 vertexUV --output "$shader_tmp/cell.frag"
printf '\000' >> "$shader_tmp/cell.metal"
{
  printf '/* SPDX-License-Identifier: BSD-3-Clause\n * Generated by tools/build-cell-shaders.sh. */\n'
  xxd -i -n hide_cell_spv "$shader_tmp/native.spv" | sed 's/^unsigned char/_Alignas(4) static const unsigned char/;s/^unsigned int/static const unsigned int/'
  xxd -i -n hide_cell_msl "$shader_tmp/cell.metal" | sed 's/^unsigned/static const unsigned/'
} > cbits/shaders/cell.generated.h
{
  printf "// SPDX-License-Identifier: BSD-3-Clause\n// Generated by tools/build-cell-shaders.sh.\nconst hideCellFragment = String.raw\140"
  cat "$shader_tmp/cell.frag"
  printf '\140;\n'
} > assets/web/cell-shader.js
